### ISSUE TITLE
Have a way to not overshoot Letsencrypt cert creation limit

### ISSUE THREAD

**Issue by tasdikrahman** [gojekfarm/kingsly#32]
There is no logic as of now which would allow for a cooldown period before kingsly requests for certs from letsecrypt servers, in case kingsly hits that limit. It would be rate limited.

**Comment by BimoZX** [comment]
I'll take a stab at this. After seeing the code, and looking at the rate limit documentation (https://letsencrypt.org/docs/rate-limits/) I think we can go with the following approach for the rate-limiting:
- Add a rate-limit config, let's say `CERT_BUNDLE_WEEKLY_RATE_LIMIT`
- Make a model to track each renewal effort
- Count how many renewal efforts have been done in a week (because the rate limit is weekly in a sliding window manner) against the new config
- Throw an error when the renewal efforts is more or equal to the config
- Let the renewal through when it's less

What do you think?

**Comment by olttwa** [comment]
@BimoZX @tasdikrahman I checked the docs of letsencrypt, and kingsly's implementation.

> If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 5,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate. Note: For performance and reliability reasons, it’s better to use fewer names per certificate whenever you can.


> Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a Duplicate Certificate limit of 5 per week. Note: renewals used to count against your Certificate per Registered Domain limit until March 2019, but they don’t anymore.

> A certificate is considered a renewal (or a duplicate) of an earlier certificate if it contains the exact same set of hostnames, ignoring capitalization and ordering of hostnames. For instance, if you requested a certificate for the names [www.example.com, example.com], you could request four more certificates for [www.example.com, example.com] during the week. If you changed the set of hostnames by adding [blog.example.com], you would be able to request additional certificates.

Currently, above specified rate-limits won't be reached.

**Comment by olttwa** [comment]
The problem we're looking to solve is `idempotency`. On request of a cert bundle creation, kingsly tries to create a new cert every single time. [Ref](https://github.com/gojek/kingsly/blob/master/app/models/v1/cert_bundle.rb#L5)

Instead of creating a cert on every request, Kingsly should first check the expiry of the cert. 

If cert is about to expire in x days/months, renew it.
Else, return the existing cert bundle.

**Comment by olttwa** [comment]
@tasdikrahman @BimoZX if it makes sense to you, let's close #34 #32 

We can create a new issue to address [this](https://github.com/gojek/kingsly/issues/32#issuecomment-519820362)

**Comment by BimoZX** [comment]
Hi @olttwa, cmiiw @tasdikrahman the current kingsly is already doing that, it won't renew unless it hits the configured expiry time ([here](https://github.com/gojek/kingsly/blob/master/app/models/v1/cert_bundle.rb#L8)). It won't hit LE server if `self.needs_renewal?` is `false`.

**Comment by olttwa** [comment]
@BimoZX thanks for pointing this out. 

I'll close #34 #32 then.

**Comment by tasdikrahman** [comment]
closing this as discussed above https://github.com/gojek/kingsly/issues/32#issuecomment-519823034
